<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>nexaIQ Connector</AssemblyName>
    <RootNamespace>NexaIQ.Connector</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NexaIQ.Connector.Core\NexaIQ.Connector.Core.csproj" />
  </ItemGroup>
</Project>
